import type { ArmyUnitDefinition } from '../types';

export const armyUnits: ArmyUnitDefinition[] = [
  {
    key: 'dronePillard',
    name: 'Drone Pillard',
    description: 'Unité rapide, idéale pour pillage rapide.',
    prereqs: { construction: { factory: 1 }, tech: { fabricationTech: 1 } },
    baseCost: { data: 150, cpu: 50, bandwidth: 60 },
    baseTime: 45,
    attack: 5,
    defense: 2,
    speed: 10,
    capacity: 100,
  },
  {
    key: 'gardienNumerique',
    name: 'Gardien Numérique',
    description: 'Unité de défense solide.',
    prereqs: { construction: { factory: 2 }, tech: { defenseTech: 1 } },
    baseCost: { data: 300, cpu: 120, bandwidth: 50 },
    baseTime: 80,
    attack: 4,
    defense: 10,
    speed: 4,
  },
  {
    key: 'agentEspion',
    name: 'Agent Espion',
    description: 'Unité pour espionner les Nodes ennemis.',
    prereqs: { construction: { researchLab: 2 }, tech: { espionnageTech: 1 } },
    baseCost: { data: 200, cpu: 80, bandwidth: 100 },
    baseTime: 90,
    attack: 1,
    defense: 1,
    speed: 12,
    effect: 'espionnage',
  },
  {
    key: 'hackerVR',
    name: 'Hacker VR',
    description: 'Désactive temporairement les défenses ennemies.',
    prereqs: { construction: { researchLab: 3 }, tech: { hackingTech: 1 } },
    baseCost: { data: 400, cpu: 220, bandwidth: 150 },
    baseTime: 120,
    attack: 0,
    defense: 3,
    speed: 8,
    effect: 'sabotage',
  },
  {
    key: 'titanDigital',
    name: 'Titan Digital',
    description: 'Unité puissante et résistante pour les attaques majeures.',
    prereqs: { construction: { factory: 4 }, tech: { heavyArmorTech: 1 } },
    baseCost: { data: 1200, cpu: 700, bandwidth: 250 },
    baseTime: 600,
    attack: 40,
    defense: 25,
    speed: 3,
    capacity: 400,
  },
  {
    key: 'chasseurNumerique',
    name: 'Chasseur Numérique',
    description: 'Unité d\'interception rapide, efficace contre les drones pillards.',
    prereqs: { construction: { factory: 2 }, tech: { interceptionTech: 1 } },
    baseCost: { data: 250, cpu: 110, bandwidth: 120 },
    baseTime: 70,
    attack: 8,
    defense: 5,
    speed: 11,
  },
  {
    key: 'bombardierVirtuel',
    name: 'Bombardier Virtuel',
    description: 'Unité spécialisée dans la destruction des défenses adverses.',
    prereqs: { construction: { factory: 3 }, tech: { demolitionTech: 1 } },
    baseCost: { data: 600, cpu: 260, bandwidth: 150 },
    baseTime: 180,
    attack: 25,
    defense: 8,
    speed: 5,
    effect: 'bonusVSDefense',
  },
  {
    key: 'transporteurVR',
    name: 'Transporteur VR',
    description: 'Unité de transport, essentielle pour piller de grandes quantités de ressources.',
    prereqs: { construction: { factory: 3 }, tech: { logisticsTech: 1 } },
    baseCost: { data: 500, cpu: 180, bandwidth: 200 },
    baseTime: 200,
    attack: 2,
    defense: 6,
    speed: 6,
    capacity: 1000,
  },
  {
    key: 'fregateNumerique',
    name: 'Frégate Numérique',
    description: 'Unité polyvalente pour attaques et défenses équilibrées.',
    prereqs: { construction: { factory: 3 }, tech: { fabricationTech: 2 } },
    baseCost: { data: 800, cpu: 350, bandwidth: 160 },
    baseTime: 300,
    attack: 18,
    defense: 12,
    speed: 6,
  },
  {
    key: 'croiseurDigital',
    name: 'Croiseur Digital',
    description: 'Unité lourde, très puissante contre les unités moyennes.',
    prereqs: { construction: { factory: 4 }, tech: { heavyArmorTech: 2 } },
    baseCost: { data: 2000, cpu: 950, bandwidth: 400 },
    baseTime: 1000,
    attack: 55,
    defense: 35,
    speed: 4,
    effect: 'bonusVSFrigate',
  },
  {
    key: 'cuirasseVirtuel',
    name: 'Cuirassé Virtuel',
    description: 'Unité ultra-puissante pour dominer les champs de bataille majeurs.',
    prereqs: { construction: { factory: 5 }, tech: { heavyArmorTech: 3 } },
    baseCost: { data: 5000, cpu: 2400, bandwidth: 1000 },
    baseTime: 2500,
    attack: 120,
    defense: 75,
    speed: 2,
    capacity: 3000,
  },
];
